export const deployedDummyData = [
    {
        id: 1,
        "BANK NAME": "SANIMA",
        "REQUESTED DATE": "26-Oct-21",
        "REQUEST TYPE": "DEPLOY",
        "MERCHANT NAME": "SAMAY RESTAURANT",
        "ADDRESS 1": "LAKESIDE",
        "ADDRESS 2": "KASKI",
        "TERMINAL ID": 33330924,
        "MERCHANT ID": 461002292629258,
        "MODEL": "3G WIFI",
        "FINAL KCV": "DCD64F",
        "KEY INDEX": 884,
        "CONTACT NUMBER": 9851094101,
        "CONTACT PERSON": "NIRU THAPA",
        "REMARKS": "3G",
        "Status": "Deployed"
    },
    {
        id: 2,
        "BANK NAME": "SANIMA",
        "REQUESTED DATE": "28-Oct-21",
        "REQUEST TYPE": "REPLACE",
        "MERCHANT NAME": "JWALA AUTO MOBILES",
        "ADDRESS 1": "LATIKOILI",
        "ADDRESS 2": "SURKHET",
        "TERMINAL ID": 33330912,
        "MERCHANT ID": 461002337744393,
        "MODEL": "3G WIFI",
        "FINAL KCV": "DCD64F",
        "KEY INDEX": 884,
        "CONTACT NUMBER": 9858052528,
        "CONTACT PERSON": "HARKA BAHADUR CHAUDHARY",
        "REMARKS": "",
        "Status": "Pending"
    },
    {
        id: 3,
        "BANK NAME": "GLOBAL",
        "REQUESTED DATE": "28-Oct-21",
        "REQUEST TYPE": "REPLACE",
        "MERCHANT NAME": "JWALA AUTO MOBILES",
        "ADDRESS 1": "LATIKOILI",
        "ADDRESS 2": "SURKHET",
        "TERMINAL ID": 33330912,
        "MERCHANT ID": 461002337744393,
        "MODEL": "3G WIFI",
        "FINAL KCV": "DCD64F",
        "KEY INDEX": 884,
        "CONTACT NUMBER": 9858052528,
        "CONTACT PERSON": "HARKA BAHADUR CHAUDHARY",
        "REMARKS": "",
        "Status": "Pending"
    }
]